# Don't change this! Version used to track needed updates.
version = 0
attackedChickenFeathers = true
attackedParrotFeathers = true
attackedSnowGolemSnowflakes = true
attackedSheepFluff = true
attackedSlimeSlime = true
allayMagicDensity = 0.2
vexMagicDensity = 0.2
sheepShearFluff = true
improvedDragonFireballTrail = true
dragonsBreathClouds = true
commandBlockMinecartParticles = "ON"
endCrystalParticles = true
minecartSparksDisplayType = "DEFAULT"
minecartSparksDensity = 0.149783
slimeTrails = false
magmaCubeTrails = false
replaceSlimeSquishParticles = true
replaceOozingEffectParticles = true
replaceSpellCasterParticles = true
ironGolemCrackParticles = true
spectralArrowParticles = true
wardenDeathSoulParticles = true
freezingSnowFlakes = true
featherTicklingPandas = true
improvedPandaSneezes = true
villagerWorkAtWorkstationParticles = true
improvedBrownMooshroomFeedingEffects = true
improvedMooshroomShearingEffects = true
replaceBlazeSmoke = true
animalFeedingParticles = true
animalFeedingSoundVolume = 1.0
underwaterEntityPoofBubbles = true
improvedWetWolfShakeEffects = true
improvedVillagerSweatingEffects = true

[sleeping]
playerSnoreChance = 0.05659654247330193
playerSnoreSoundVolume = 0.35086957
playersHaveSleepingZs = false
villagerSnoreChance = 0.1203556964254274
villagerSnoreSoundVolume = 0.35086957
villagersHaveSleepingZs = false
foxesHaveSleepingZs = false
batsHaveSleepingZs = false
catsHaveSleepingZs = false
otherMobsHaveSleepingZs = false
displaySleepingZsOnlyWhenSnoring = false
adjustNameTagWhenSleeping = true

[humanoids]
drowningBubblesDisplayType = "DEFAULT"
drowningBubblesDensity = 2
drowningBubbleAlpha = 0.59607846
forceDrowningBubblesToColumn = false
potionRingsDisplayType = "DEFAULT"
potionRingsParticleType = "BOTH"
potionRingsScale = 1.0
potionRingsAlpha = 1.0
NPCsHavePotionRings = true

[humanoids.frostyBreath]
displayType = "DEFAULT"
alpha = 0.2509804
waitTime = 121
seasons = "DEFAULT"
additionalBiomes = [  ]

[humanoids.player]
enableBreathingEffectsInCreative = true
stomachGrowlingThreshold = 6
stomachGrowlingVolume = 1.0
stomachGrowlingWaitTime = 15
heartBeatingThreshold = 6
heartbeatVolume = 1.0
heartBeatingWaitTime = 3

[dustClouds]
scale = 0.996877
alpha = 0.54904187
preventWhenRaining = true
flyIntoWall = true
lessViewBlocking = false
playerFell = true
mobFell = true
landMaceAttack = true
playerRunning = true
mobRunning = true
playerRunningRequiresSpeed = true

[burning]
smokeType = "DEFAULT"
smokeDensity = 1.0
flamesDensity = 1.0
sparksDensity = 1.0
soundVolume = 0.3
entityBlocklist = [
    "minecraft:lightning_bolt"
]
extinguishSteam = true

[explosives]
tntUpdateSmoke = true
tntFlamesDensity = 1
tntSparks = true
creeperSmoke = "UPDATED"
creeperSparks = true

[splashes]
splashEffects = true
splashRipples = true
splashDroplets = true
splashBubbles = true
explosionsCauseSplashes = true
splashOverlayTint = 0.2
splashOverlayAlpha = 0.8
splashVelocityThreshold = 0.35
entityBlocklist = [  ]
secondarySplash = true
secondarySplashRipples = false
secondarySplashVelocityThreshold = 0.3
lavaSplashes = true
lavaSplashRipples = true